# Generated by Django 5.2 on 2025-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Deck Techs'), (1, 'Combos & Strategy'), (2, 'Rules & Card Help'), (3, 'Looking for Games'), (4, 'Social & Trading')], default=0),
        ),
    ]
