# Generated by Django 5.2 on 2025-06-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
