# Generated by Django 5.2 on 2025-07-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_popular',
        ),
    ]
