# Generated by Django 5.2 on 2025-06-04 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='samples/cloudinary-icon', max_length=255, null=True, verbose_name='image'),
        ),
    ]
